/**
 * Created by LQ-XIAOLIU on 2017/5/26.
 */
var data={
    "ondutyTitle":"融媒体中心",
    "watchman":"杨跃新",
    "watchdata":[
        {
            "title":"电视",
            "data":[
                {
                    "title":"长视新闻",
                    "person":[
                        {
                            "zhiwu":"单片审看",
                            "name":"吴洪涛"
                        }
                    ]
                },
                {
                    "title":"小彤热线",
                    "person":[
                        {
                            "zhiwu":"单片审看",
                            "name":"王玉坤"
                        }
                    ]
                },
                {
                    "title":"说吧说吧",
                    "person":[
                        {
                            "zhiwu":"责编",
                            "name":"周艳"
                        }
                    ]
                }
            ]
        },
        {
            "title":"报纸",
            "data":[
                {
                    "title":"",
                    "person":[
                        {
                            "zhiwu":"统版",
                            "name":"黄庆时"
                        },
                        {
                            "zhiwu":"签版",
                            "name":"杨跃新"
                        }
                    ]
                }
            ]
        },
        {
            "title":"广播",
            "data":[
                {
                    "title":"1066早班车",
                    "person":[
                        {
                            "zhiwu":"审稿",
                            "name":"王胜国"
                        }
                    ]
                },
                {
                    "title":"整点新闻",
                    "person":[
                        {
                            "zhiwu":"审稿",
                            "name":"王婷"
                        }
                    ]
                },
                {
                    "title":"在路上",
                    "person":[
                        {
                            "zhiwu":"审稿",
                            "name":"王婷"
                        }
                    ]
                },
                {
                    "title":"新闻连连看",
                    "person":[
                        {
                            "zhiwu":"审稿",
                            "name":"吴楠"
                        }
                    ]
                }
            ]
        },
        {
            "title":"融媒体",
            "data":[
                {
                    "title":"",
                    "person":[
                        {
                            "zhiwu":"广播连线",
                            "name":"朱宁辉"
                        },
                        {
                            "zhiwu":"即时报",
                            "name":"张珊"
                        }
                    ]
                }
            ]
        }
    ]
};